### ISSUE TITLE
Error running built app on macs

### ISSUE THREAD

**Issue by jordanfb** [jordanfb/PicoCADToolKit#11]
Built app fails to run on M1 mac Sonoma 14.6.1.
It just hops and doesn't do anything, and if dragged into terminal it says "killed" and nothing else. Helpful! Logging this here.

**Comment by jordanfb** [comment]
It's being built on:
macos-latest, which is an m1 mac running:
macOS 14
OS Version: macOS 14.7.1 (23H222)
Kernel Version: Darwin 23.6.0
Image Version: 20241125.421

**Comment by shieldyguy** [comment]
same issue here on sequoia 15.1, M2 Max

**Comment by jordanfb** [comment]
Part of the problem is I don’t have a Mac to build/test it on so I’ve had to just hope that GitHub actions will build it correctly (and apparently the answer is no). 

Running the Python code directly should work totally fine with very low effort if you want to try that. With no pressure whatsoever if you do end up trying it you can also build it into a .app file on your machine which we could try distributing.

**Comment by shieldyguy** [comment]
hah I had to do a lot of dancing to get tkinter working! did though, got the toolkit running, but unfortunately there's some issue and I can't load a file. any kind of log I can look at or share with you?

**Comment by jordanfb** [comment]
If you are running it via the command line then theoretically it'll log all the errors to the command line so you could copy and paste me the output of the command line. It will probably mention an error about loading a specific file (I think it's called train or train station) which is a demo file I use for testing so that one doesn't matter. But if you can't load any of your own files then that's definitely a problem!

**Comment by shieldyguy** [comment]
2025-05-07 18:35:39.035 Python[72880:172229233] +[IMKClient subclass]: chose IMKClient_Modern
2025-05-07 18:35:39.035 Python[72880:172229233] +[IMKInputSession subclass]: chose IMKInputSession_Modern
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/tkinter/__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "/pico-8/picocad/PicoCADToolKit-main/toolkitui.py", line 807, in choose_filename_dialog
    self.picoToolData.set_filepath(self.filename)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/pico-8/picocad/PicoCADToolKit-main/toolkitui.py", line 114, in set_filepath
    self.notify_picoSave_listeners() # I guess do this here? The listeners have to be capable of accepting None as a save
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/pico-8/picocad/PicoCADToolKit-main/toolkitui.py", line 141, in notify_picoSave_listeners
    f(self.picoSave)
    ~^^^^^^^^^^^^^^^
  File "/pico-8/picocad/PicoCADToolKit-main/toolkitui.py", line 874, in <lambda>
    self.picoToolData.add_picoSave_listener(lambda x: self.calculate_stats())
                                                      ~~~~~~~~~~~~~~~~~~~~^^
  File "/pico-8/picocad/PicoCADToolKit-main/toolkitui.py", line 954, in calculate_stats
    without_texture, raw = self.picoToolData.picoSave.estimate_file_size()
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/pico-8/picocad/PicoCADToolKit-main/picoCADParser.py", line 1147, in estimate_file_size
    file_text = self.output_save_text(self.original_path) # this is incorrect but it works
  File "/pico-8/picocad/PicoCADToolKit-main/picoCADParser.py", line 1160, in output_save_text
    o += "\n" + obj.output_save_text() + ","
                ~~~~~~~~~~~~~~~~~~~~^^
  File "/pico-8/picocad/PicoCADToolKit-main/picoCADParser.py", line 1085, in output_save_text
    o = "{\n name='" + self.name + "', pos={" + ",".join([float_to_str(x) for x in self.pos]) + "}, rot={" + ",".join([float_to_str(x) for x in self.rot]) +"},\n v={"
                                                                                   ^^^^^^^^
TypeError: 'SimpleVectorIter' object is not iterable


I had claude try to fix it on my machine lol... not certain if it's just a bandaid or what. 

	def __iter__(iterself):
		return iterself

on or about line 1566 in picoCADParser.py

**Comment by jordanfb** [comment]
Any chance you can send the file you're trying to edit? I've tried to reproduce this but haven't been able to so I'm wondering if it's file specific or if there's something else going on with me running on Windows. Seems like it's easiest to eliminate the possibility of it being file specific first.

I'm running Python 3.12.3 (if you go to terminal and type `python3 -V` it'll print the version you're running. It would also be helpful to know what version you're running thanks!
