### ISSUE TITLE
uv unwrap fails on some models

### ISSUE THREAD

**Issue by jordanfb** [jordanfb/PicoCADToolKit#8]
submitted by ricebowl.1 on the discord --
they encountered it with this file:
[vjr_backup_uv_unwrap_bug.txt](https://github.com/user-attachments/files/16894464/vjr_backup_uv_unwrap_bug.txt)
They sent the following message:

```
I keep getting the 
"ERROR THERE AREN'T ENOUGH UNIQUE VERTICES OOPS
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter_init.py", line 1948, in call_
  File "toolkitUI.py", line 2636, in unwrap_model
  File "picoCADParser.py", line 287, in test_create_normals
  File "picoCADParser.py", line 278, in get_scaled_projected_points_to_distance
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'" 
error when i try to uv unwrap my model, does anyone know how to fix this? 
```

**Comment by jordanfb** [comment]
Fixed this and improved the error into a warning instead since I made the math better as well.
